apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: bank-of-anthos

build:
  artifacts:
    - image: us-central1-docker.pkg.dev/oracle169-website/risk-agent
      context: src/risk-agent
    - image: us-central1-docker.pkg.dev/oracle169-website/frontend/frontend
      context: src/frontend
  tagPolicy:
    gitCommit: {}

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml

portForward:
  - resourceType: service
    resourceName: risk-agent
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: frontend
    port: 80
    localPort: 8081
