apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk-agent
  template:
    metadata:
      labels:
        app: risk-agent
    spec:
      containers:
      - name: risk-agent
        image: us-central1-docker.pkg.dev/YOUR_PROJECT_ID/bank-of-anthos/risk-agent
        env:
        - name: PROJECT_ID
          value: "oracle69-website"
        - name: LOCATION
          value: "us-central1"
        ports:
        - containerPort: 8080
