apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k8s/base/frontend-deployment.yaml
  - k8s/base/frontend-service.yaml
  - k8s/base/risk-agent-deployment.yaml
  - k8s/base/risk-agent-service.yaml
